name: docs

on:
  push:
    tags: ["*"]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: write

jobs:
  docs:
    concurrency:
      group: docs
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5  # @v2.0.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            docs.python.org:443
            docs.sqlalchemy.org:443
            files.pythonhosted.org:443
            github.com:443
            objects.githubusercontent.com:443
            pypi.org:443
            redis-py.readthedocs.io:443
            starlite-api.github.io:443
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b  # @v3.2.0
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@5ccb29d8773c3f3f653e1705f474dfaa8a06a912  #v4.4.0
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade wheel tox
      - id: get-version
        run: |
          version=$(python -c 'print("${{github.ref_name}}".rsplit(".", 1)[0])')
          echo "::set-output name=version::$version"
      - name: Build docs website and API reference
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          tox -e docs -- deploy --push ${{steps.get-version.outputs.version}}
