name: docs

on:
  push:
    tags: ["*"]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: write

jobs:
  docs:
    concurrency:
      group: docs
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969  # @v2.4.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            docs.python.org:443
            docs.sqlalchemy.org:443
            files.pythonhosted.org:443
            github.com:443
            objects.githubusercontent.com:443
            pypi.org:443
            redis-py.readthedocs.io:443
            starlite-api.github.io:443
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # @v3.5.2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0  #v4.6.1
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade wheel tox
      - id: get-version
        run: |
          version=$(python -c 'print("${{github.ref_name}}".rsplit(".", 1)[0])')
          echo "::set-output name=version::$version"
      - name: Build docs website and API reference
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          tox -e docs -- deploy --push ${{steps.get-version.outputs.version}}
