name: docs

on:
  push:
    tags: ["*"]

jobs:
  docs:
    concurrency:
      group: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade wheel tox
      - id: get-version
        run: |
          version=$(python -c 'print("${{github.ref_name}}".rsplit(".", 1)[0])')
          echo "::set-output name=version::$version"
      - name: Build docs website and API reference
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          tox -e docs -- deploy --push ${{steps.get-version.outputs.version}}
