name: docs

on:
  push:
    tags: ["*"]

permissions:
  contents: read

jobs:
  docs:
    concurrency:
      group: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: python -m pip install --upgrade wheel tox
      - name: Build docs website and API reference
        run: |
          tox -e docs -- deploy --push --update-aliases ${{github.ref_name}}
          tox -e docs -- set-default --push latest
